variable "label_repository" {}
variable "label_color_bug" {}
variable "label_name_bug" {}
variable "label_description_bug" {}
variable "label_color_enhancement" {}
variable "label_name_enhancement" {}
variable "label_description_enhancement" {}
variable "label_color_cleanup" {}
variable "label_name_cleanup" {}
variable "label_description_cleanup" {}
variable "label_color_question" {}
variable "label_name_question" {}
variable "label_description_question" {}
variable "label_color_area" {}
variable "label_name_copy" {}
variable "label_description_copy" {}
variable "label_name_testing" {}
variable "label_description_testing" {}
variable "label_name_terraform_module" {}
variable "label_description_terraform_module" {}
variable "label_name_terraform_control" {}
variable "label_description_terraform_control" {}
variable "label_color_status" {}
variable "label_name_blocked" {}
variable "label_description_blocked" {}
variable "label_name_needs_investigation" {}
variable "label_description_needs_investigation" {}
variable "label_name_in_progress" {}
variable "label_description_in_progress" {}
