variable "label_repository" {}
variable "label_color_bug" {}
variable "label_name_bug" {}
variable "label_description_bug" {}
variable "label_color_enhancement" {}
variable "label_name_enhancement" {}
variable "label_description_enhancement" {}
variable "label_color_cleanup" {}
variable "label_name_cleanup" {}
variable "label_description_cleanup" {}
variable "label_color_question" {}
variable "label_name_question" {}
variable "label_description_question" {}
variable "label_color_area" {}
variable "label_name_copy" {}
variable "label_description_copy" {}
variable "label_name_testing" {}
variable "label_description_testing" {}
variable "label_name_api" {}
variable "label_description_api" {}
variable "label_name_policy_engine" {}
variable "label_description_policy_engine" {}
variable "label_name_scaling" {}
variable "label_description_scaling" {}
variable "label_name_autoscaling" {}
variable "label_description_autoscaling" {}
variable "label_name_security" {}
variable "label_description_security" {}
variable "label_name_cli" {}
variable "label_description_cli" {}
variable "label_name_ui" {}
variable "label_description_ui" {}
variable "label_name_build" {}
variable "label_description_build" {}
variable "label_name_leadership" {}
variable "label_description_leadership" {}
variable "label_name_storage" {}
variable "label_description_storage" {}
variable "label_name_scaling_state" {}
variable "label_description_scaling_state" {}
variable "label_name_client_provider" {}
variable "label_description_client_provider" {}
variable "label_color_status" {}
variable "label_name_blocked" {}
variable "label_description_blocked" {}
variable "label_name_needs_investigation" {}
variable "label_description_needs_investigation" {}
variable "label_name_in_progress" {}
variable "label_description_in_progress" {}
